### ISSUE TITLE
ERROR TO IMPORT

### ISSUE THREAD

**Issue by joseliko7** [fastbootmobile/encore#16]
Error to import, gradle failed.

check error:

Error:(1, 0) Plugin with id 'com.android.application' not found.
![1](https://cloud.githubusercontent.com/assets/13633032/10121388/4693b2fc-64e9-11e5-9960-409f5aa4dbf5.jpg)

**Comment by maxwen** [comment]
+1 :)

**Comment by yuva-dev** [comment]
try adding the following in your build.gradle

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

**Comment by ZuzooVn** [comment]
`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: com.fastbootmobile.encore.app:main, PID: 1635
                                                                                  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.fastbootmobile.encore.app-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libc++_shared.so"
                                                                                      at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                                      at java.lang.System.loadLibrary(System.java:989)
                                                                                      at com.fastbootmobile.encore.service.NativeHub.<clinit>(NativeHub.java:46)
                                                                                      at com.fastbootmobile.encore.service.PlaybackService.onCreate(PlaybackService.java:255)
                                                                                      at android.app.ActivityThread.handleCreateService(ActivityThread.java:2731)
                                                                                      at android.app.ActivityThread.access$1800(ActivityThread.java:144)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1361)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)`

I have this problem in runtime!!!

**Comment by asaflevi1983** [comment]
Did you find a solution for the runtime issue : **couldn't find "libc++_shared.so"**
